---
- name: Configure apache2
  hosts: all
  tasks:
    - name: Calling multiple playbooks for apache2
      include_tasks: "{{item}}"
      with_items:
       - install.yml
       - edit_index.yml
       - restart.yml
       - check_url_response.yml
...
