---
- name: Error handling / Exception handling
  hosts: all
  tasks:
    - block:
      - name: Install git using apt
        apt:
          name: git
          state: present
          update_cache: yes
      rescue:
      - name: Install git using zypper
        zypper:
          name: git
          state: present
          update_cache: yes
      always:
      - name: Display software status
        debug:
          msg: " Software installation successful "
...           
