---
- name: check if f1 folder is present if not create f1 file
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: check f1 folder
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Create a f1 file if f1 folder is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false  
...
