---
- name: check if file1 is excutableif yes delete it
  hosts: all
  tasks:
    - name: check output info
      stat:
        path: /tmp/file1
      register: results
    - name: Display output for above module
      debug:
        var: results
    - name: delete file if executable
      file:
        name: /tmp/file1
        state: absent
      when: results.stat.executable == true
      tags: Deleting Executable File
...
