---
- name: setup required s/w's for jenkins
  hosts: jenkinsserver
  tasks: 
     - name: install necessary s/w's 
       apt:
         name: "{{item.a}}"
         state: "{{item.b}}"
         update_cache: "{{item.c}}"
       with_items:
          - {a: openjdk-11-jdk, b: present, c: yes}
          - {a: git, b: present, c: no}
          - {a: maven, b: present, c: no}
     - name: Download jenkins.war
       get_url:
         url: https://get.jenkins.io/war-stable/2.426.1/jenkins.war
         dest: /home/ubuntu
- name: Install qa & prod s/w's
  hosts: servers
  tasks:
    - name: install tomcat9 & tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat9, b: present, c: yes}
        - {a: tomcat9-admin, b: present, c: no}
        - {a: openjdk-11-jdk, b: absent, c: no}
        - {a: git, b: absent, c: no}
        - {a: maven, b: absent, c: no}
    - name: Copy tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
      notify: Restart tomcat9
  handlers:
    - name: Restart tomcat9
      service:
        name: tomcat9
        state: restarted
...
