---
- name: Implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: install software
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: yes}
        - {a: maven,b: present,c: yes}
        - {a: git,b: present,c: yes}
      tags: Software Installation
    - name: create user
      user:
        name: sayali
        password: admin
      tags: User creation
    - name: create a file
      file:
        name: /tmp/devops
        state: touch
...
