---
- name: Install / Un-install softwares
  hosts: all
  tasks: 
     - name: install s/w
       apt:
         name: "{{item}}"
         state: present
         update_cache: yes
       with_items: 
         - tree
         - maven
         - git
...
