---
- name: fetch file from server1
  hosts: 172.31.2.190
  tasks: 
   - name: Fetch file
     fetch:
      src: file200
      dest: /tmp
- name: Copy file to server2
  hosts: 172.31.2.43
  tasks:
    - name: copy file
      copy:
       src: /tmp/172.31.2.190
       dest: /tmp
...
