---
- name: Capture OS info
  hosts: all
  tasks:
   - name: OS info
     debug:
       msg: "{{ansible_distribution}}"
   - name: Capture OS version
     debug:
       msg: "{{ansible_distribution_version}}"
   - name: Capture major version
     debug:
       msg: "{{ansible_distribution_major_version}}"
...


