---
- name: Implementing host scope variables
  hosts: devservers
  tasks:
    - name: install/ un-install s/w
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
